#! /bin/sh

bspc monitor -d 1 2 3 4 5

# Border Propoetions
bspc config border_width        3
bspc config window_gap          6
bspc config border_radius       15
bspc config split_ratio          0.5

# Border Color
bspc config focused_border_color "#7AA2F7"
bspc config active_border_color  "#7dcfff"
bspc config normal_border_color  "#868da9"

# Window Behavior
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a barve desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Peek state=floating
#bspc rule -a conky-manager2 state=floating
#bspc rule -a Plank manager=off border=off locked=on focus=off follow=off layer=above
#bspc rule -a Rofi state=floating
#bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off focus=off center=true follow=off rectangle=1920x1080+0+0
bspc config external_rules_command "$HOME/.config/bspwm/scripts/external-rules"

# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# BSP Layout 
sleep 10 && $HOME/.config/bspwm/scripts/bspfloat floating 5 &> $HOME/.log.bspfloat.txt &

# Polybar
~/.config/polybar/launch.sh &

# EWW
eww daemon &

# sxhkd (Hot Key Deamon)
killall -q sxhkd; sxhkd &

# Wallpaper
DISPLAY=:0 feh --bg-scale --randomize ~/Pictures/Wallpapers/*

# Notifications
# /usr/bin/dunst &
killall -q dunst; dunst -conf ~/.config/dunst/dunstrc &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Picom
# picom -b &
killall -q picom; picom --experimental-backends --config ~/.config/picom/picom.conf &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# Power management
xfce4-power-manager &

# Dock
bash $HOME/.config/bspwm/scripts/fix-plank

ukui-window-switch &
parcellite &
plank &
